# Generated by Django 2.1.7 on 2019-03-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190320_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_of_comment']},
        ),
    ]
